<?php

function pushy_uninstall() {
  $token_types = ['Expo', 'IOS', 'Android'];
  
  $update_manager = Drupal::service('entity.definition_update_manager');

  foreach ($fields as $field) {
    $definition = $update_manager
      ->getFieldStorageDefinition('push_notification_device_token_' strtolower($field), 'user');
    
    $update_manager->uninstallFieldStorageDefinition($definition);
  }

  return t('The Expo, IOS and Android token fields have been removed from the user entity type.');
}